rules:
  preset-japanese: true
  preset-ja-technical-writing:
    max-kanji-continuous-len:
      allow:
        - '倍精度浮動小数点数'
        - '自己署名証明書'
        - 料金受取人払等
        - 私書箱利用事業所
        - 料金受取人払
        - 一部事務組合等
        - 全国地方公共団体
        - 政令指定都市施行
        - 郵便区調整等
        - 日本郵便株式会社
        - 大口事業所名
        - 大口事業所名
        - 個別番号種別


